name: unified_http_client
description: "A Flutter Package to provide smooth Api call with All Error and Exception handeled."
version: 0.0.6
homepage: https://github.com/Abhinimap/unified_http_client/tree/main
repository: https://github.com/Abhinimap/unified_http_client

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
